### PR TITLE
Add initial support for CLISP

### PR DESCRIPTION
**Pull request by Sasanidas**

### CODE REVIEW

**Comment by cxxxr** [comment]
Hmm, Wouldn't it be too expensive to maintain to support even a processing system that hasn't been released in 13 years of quicksand?

**Comment by Sasanidas** [comment]
As far as I know, is still being developed here(https://gitlab.com/gnu-clisp/clisp)

**Comment by Sasanidas** [comment]
But it's true that the main page doesn't have the information updated, so it seems like its an abandon implementation

**Comment by Sasanidas** [comment]
It doesn't make too much sense to add support for CLISP for now (more info https://github.com/lem-project/lem/pull/686#issuecomment-1595692945)

**Pull request closed without merging**
